# Generated by Django 5.1.6 on 2025-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
