# Generated by Django 5.1.6 on 2025-03-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactmessage_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
